development:
  adapter: postgresql
  encoding: unicode
  database: quiz_development
  pool: 5
  host: localhost
  username: <%= ENV.fetch("POSTGRES_USER", `whoami`) %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", '') %>

test:
  adapter: postgresql
  encoding: unicode
  database: quiz_test
  pool: 5
  username: <%= ENV.fetch("POSTGRES_USER", `whoami`) %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", '') %>

staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  url: <%= ENV['DATABASE_URL'] %>
